### ISSUE TITLE
Resolf error

### ISSUE THREAD

**Issue by ntimo** [pozgo/docker-teamspeak#1]
I always get this error when I try to run your docker image.
Could you please help me with it?

Resolving dl.4players.de (dl.4players.de)... failed: Name or service not known.
wget: unable to resolve host address 'dl.4players.de'

Thanks,
Timo

**Comment by pozgo** [comment]
HI. Please make sure that your host os that runs docker daemon have a valid internet connection and gateway is set correctly. 

I have just run it and works fine. Otherwise, tests would fail.

**Comment by ntimo** [comment]
from my host server where docker runs on it works fine. I can wget stuff from dl.4players.de. But in docker it does not work.

**Comment by pozgo** [comment]
I would say it's something wrong with your networking/firawall. Does any other running image have access to the internet? I need more details to debug it. 
OS/Docker version/ Docker networking/ and which command you use to deploy the image.

**Comment by ntimo** [comment]
Well how could I test it? I am running Docker using Plesk Onyx. So I am not sure what command plesk uses to start the image. The OS is Ubuntu 16.04 and Docker version 1.12.3, build 6b644ec

**Comment by pozgo** [comment]
What parameters are you using to deploy it? (volumes, ports)

**Comment by pozgo** [comment]
cannot reproduce the issue. Closing due to lack of details and after testing all seems to be working as expected.
